table users {
  id varchar(36) [pk, not null]
  name varchar(128) [not null]
  email varchar(128) [not null]
  password varchar(128) [not null]
  created_at timestamp [default: `now()`]
  updated_at datetime [not null, default: `now()`, note: 'update time']
}

table terms {
  id varchar(36) [pk, not null]
  user_id varchar(36) [not null]
  title varchar(128) [not null]
  locked_at datetime [default: null]
  created_at timestamp [default: `now()`]
  updated_at datetime [not null, default: `now()`, note: 'update time']
}

table courses {
  id varchar(36) [pk, not null]
  user_id varchar(36) [not null]
  term_id varchar(128) [not null]
  title varchar(128) [not null]
  description text
  locked_at datetime [default: null]
  created_at timestamp [default: `now()`]
  updated_at datetime [not null, default: `now()`, note: 'update time']
}

table tasks {
  id varchar(36) [pk, not null]
  course_id varchar(36) [not null]
  title varchar(128) [not null]
  description text
  created_at timestamp [default: `now()`]
  updated_at datetime [not null, default: `now()`, note: 'update time']
}

table submissions {
  id varchar(36) [pk, not null]
  user_id varchar(36) [not null]
  task_id varchar(36) [not null]
  title varchar(128) [not null]
  description text
  file_url varchar(255)
  created_at timestamp [default: `now()`]
  updated_at datetime [not null, default: `now()`, note: 'update time']
}

ref: submissions.user_id < users.id [delete: restrict, update: cascade]

ref: submissions.task_id < tasks.id [delete: restrict, update: cascade]

ref: courses.user_id < users.id [delete: restrict, update: cascade]

ref: courses.term_id < terms.id [delete: restrict, update: cascade]

ref: terms.user_id < users.id [delete: restrict, update: cascade]

ref: tasks.course_id < courses.id [delete: restrict, update: cascade]
